### ISSUE TITLE
Uncaught Guzzle\Common\Exception\RuntimeException: The PHP cURL extension must be installed to use Guzzle.

### ISSUE THREAD

**Issue by abhijagtap73** [jlaso/aws-s3-wrapper#2]
gives error me
Uncaught Guzzle\Common\Exception\RuntimeException: The PHP cURL extension must be installed to use Guzzle. in /var/www/html/amazons3/vendor/guzzle/guzzle/src/Guzzle/Http/Client.php:72 Stack trace: #0 /var/www/html/amazons3/vendor/aws/aws-sdk-php/src/Aws/Common/Client/AbstractClient.php(76): Guzzle\Http\Client->__construct('https://s3.eu-c...', Object(Guzzle\Common\Collection)) #1 /var/www/html/amazons3/vendor/aws/aws-sdk-php/src/Aws/Common/Client/ClientBuilder.php(248): Aws\Common\Client\AbstractClient->__construct(Object(Aws\Common\Credentials\Credentials), Object(Aws\S3\S3SignatureV4), Object(Guzzle\Common\Collection)) #2 /var/www/html/amazons3/vendor/aws/aws-sdk-php/src/Aws/S3/S3Client.php(214): Aws\Common\Client\ClientBuilder->build() #3 /var/www/html/amazons3/src/S3Wrapper.php(29): Aws\S3\S3Client::factory(Array) #4 /var/www/html/amazons3/src/S3Wrapper.php(47): JLaso\S3Wrapper\S3Wrapper->__construct('***...', '***...', '**...') #5 /var/www/html/amazons3/samples/basic. in /var/www/html/amazons3/vendor/guzzle/guzzle/src/Guzzle/Http/Client.php on line 72

**Comment by abhijagtap73** [comment]
Issue was in php-curl, restart apache server, its working now
